# auto starting/att tmux
if  [ "$(tty)" = "/dev/tty1" ] && ! pgrep -x i3 > /dev/null ; then 
	exec startx
fi

if which tmux >/dev/null 2>&1; then
	    #if not inside a tmux session, and if no session is started, start a new session
	test -z "$TMUX" && (tmux attach || tmux new-session)
fi

powerline-daemon -q
. /usr/lib/python3.7/site-packages/powerline/bindings/zsh/powerline.zsh

#import aliases

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="bullet-train"
BULLETTRAIN_PROMT_ROOT=true
BULLETTRAIN_PROMT_SEPERATE_LINE=true
BULLETTRAIN_PROMT_ADD_NEWLINE=true

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

###PLUGINS###
plugins=(
	colored-man-pages
	comand-not-found
	common-aliases
	cp
	man
	sudo
	ssh-agent
	tmux
	git
	zsh-syntax-highlighting

)

source $ZSH/oh-my-zsh.sh

####User configuration###

# export MANPATH="/usr/local/man:$MANPATH"
compdef gpg2=gpg

# parallel make
export NUMCPUS=`grep -c '^processor' /proc/cpuinfo`
alias pmake='time nice make -j $NUMCPUS --load-average=$NUMCPUS'

# http://www.economyofeffort.com/2014/07/04/zsh/
export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color

source ~/.oh-my-zsh/themes/zsh-syntax-highlighting.theme/zsh-syntax-highlighting.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# https://twitter.com/citizen428/status/902433159018561536
export FZF_DEFAULT_COMMAND='rg --files'

# Solarized Dark
export FZF_DEFAULT_OPTS=' --color dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254 --color info:254,prompt:37,spinner:108,pointer:235,marker:235'

#You may need to manually set your language environment
export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"
export LC_ALL=en_US.UTF-8

source "$HOME/.aliasrc"

prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
  fi
}
